# Generated by Django 4.1.6 on 2023-02-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('modified_at',)},
        ),
    ]
